### ISSUE TITLE
Question: Heltec w/ integrated I2C

### ISSUE THREAD

**Issue by qwksilver** [return5/DS1803#1]
some examples and info here: https://github.com/HelTecAutomation/Heltec_ESP32

The question I have is this, I have tried a few libraries to talk to this digipot on pins 21 & 22 of this device.  The defalt wire.begintransmision is the same i2c with the built in oled also on pins 4 & 15.  In the example they use wire1.begintransmission for talking to the extra interface.  I still need a library to bring it all together, is this easy modded by just making those changes in the code and making sure heltec.h is enabled, or will I need to do more?

**Comment by return5** [comment]
i dont have any experience with the Heltec_ESP32, i will have to dig into the documentation to give you a precise answer. 

let me just clarify that i understand your questions.  you want to use a ds1803 and a Heltec at the same time with the same arduino and you are asking if this will be easily done by using this library and the Heltec one together?

**Comment by qwksilver** [comment]
no arduino, the heltec replaces the arduino functionality
the problem is the onboard lcd is hardwired to the i2c on pins 4 & 15, so i need to use i2c1 i think on pins 21 & 22
i did attach to 4&15 and discovered the ds1803, but if i try to use them both on the same pins they don't do well, timing i think.

**Comment by return5** [comment]
i found this thread which might help you, specifically see the responses of travellingkiwi, canadaduane, and r1k:
https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series/issues/62

**Comment by qwksilver** [comment]
i think i have killed the ds1803, now need to wait on a spare shm, the article was inspiring, and i think i can fix the code to make it work, however i have lost access to the ds1803 which was answering the i2c checker that heltec had on their site.

**Comment by return5** [comment]
when the spare comes in let me know if it works, if it does ill mark this issue closed.

**Comment by qwksilver** [comment]
the new chip is in, adding a 2k pullup, and running the tester found the chip, and incorporating a modified (on my fork) version of this library to call to wire1 allows it talk to the ds1803 on the bus not used by the lcd.  If you want to note, and link to my fork for anyone that finds this feel free, but since I have no outstanding issue at this point I am closing this.
